spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      client:
        reactive:
          endpoints: 127.0.0.1:9300
  elasticsearch:
    rest:
      uris:
        - 127.0.0.1:9200
      connection-timeout: 1s
      read-timeout: 30s


server:
  port: 9020
