eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@127.0.0.1:8761/eureka/,http://admin:123456@127.0.0.1:8762/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
    preferIpAddress: true
prefer-ip-address: true