server:
  port: 8081
spring:
  application:
    name: layui
  thymeleaf:
#    enabled: true
    cache: false
    check-template-location: true
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    encoding: utf-8
#  mvc:
#    static-path-pattern: /static/**