initialSize: 5
jasypt:
  encryptor:
    password: salt
timeBetweenEvictionRunsMillis: 60000
maxActive: 20
maxIdle: 100
maxWait: 60000
minEvictableIdleTimeMillis: 300000
minIdle: 5
sharding:
  jdbc:
    config:
      sharding:
        default-database-strategy:
          inline:
            algorithm-expression: ds$->{user_id % 4}
            sharding-column: user_id
        defaultDataSourceName: ds0
        props:
          sql:
            show: true
        tables:
          t_order:
            actual-data-nodes: ds$->{0..3}.t_order_000$->{0..1}
            table-strategy:
              inline:
                algorithm-expression: t_order_000$->{order_id % 2}
                sharding-column: order_id
    datasource:
      ds0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: ${initialSize}
        maxActive: ${maxActive}
        maxWait: ${maxWait}
        minEvictableIdleTimeMillis: ${minEvictableIdleTimeMillis}
        minIdle: ${minIdle}
        password: ENC(AdMtUwq6xmlbAc4vHzblyg==)
        timeBetweenEvictionRunsMillis: ${timeBetweenEvictionRunsMillis}
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://111.230.6.24:3306/db_00?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
        username: root
        validationQuery: SELECT 1 FROM DUAL
      ds1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: ${initialSize}
        maxActive: ${maxActive}
        maxWait: ${maxWait}
        minEvictableIdleTimeMillis: ${minEvictableIdleTimeMillis}
        minIdle: ${minIdle}
        password: ENC(AdMtUwq6xmlbAc4vHzblyg==)
        timeBetweenEvictionRunsMillis: ${timeBetweenEvictionRunsMillis}
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://111.230.6.24:3306/db_01?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
        username: root
        validationQuery: SELECT 1 FROM DUAL
      ds2:
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: ${initialSize}
        maxActive: ${maxActive}
        maxWait: ${maxWait}
        minEvictableIdleTimeMillis: ${minEvictableIdleTimeMillis}
        minIdle: ${minIdle}
        password: ENC(AdMtUwq6xmlbAc4vHzblyg==)
        timeBetweenEvictionRunsMillis: ${timeBetweenEvictionRunsMillis}
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://111.230.6.24:3306/db_02?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
        username: root
        validationQuery: SELECT 1 FROM DUAL
      ds3:
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: ${initialSize}
        maxActive: ${maxActive}
        maxWait: ${maxWait}
        minEvictableIdleTimeMillis: ${minEvictableIdleTimeMillis}
        minIdle: ${minIdle}
        password: ENC(AdMtUwq6xmlbAc4vHzblyg==)
        timeBetweenEvictionRunsMillis: ${timeBetweenEvictionRunsMillis}
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://111.230.6.24:3306/db_03?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
        username: root
        validationQuery: SELECT 1 FROM DUAL
      names: ds0,ds1,ds2,ds3

